const WHATSAPP_NUMBER='254789872543';
const PAYBILL='222111';
const ACCOUNT='3072428';
const DELIVERY_AREAS=[
  {area:'Malindi Shop Pickup',fee:0},{area:'Malindi Town Delivery',fee:100},{area:'Gongoni',fee:100},{area:'Watamu',fee:300},{area:'Marereni',fee:300},{area:'Adu',fee:450},{area:'Marafa',fee:500},{area:'Lango Baya',fee:600}
];
const $=(s,r=document)=>r.querySelector(s);
const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=(v='')=>String(v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');
const money=v=>v!==null&&v!==''&&Number.isFinite(Number(v))?`KSh ${Number(v).toLocaleString()}`:'Ask price';
const imgs=i=>Array.isArray(i.images)&&i.images.length?i.images:[i.image].filter(Boolean);
const thumb=i=>i.thumb||i.image||imgs(i)[0]||'';
const inStock=i=>i.stockStatus!=='out'&&Number(i.stockQty)!==0;
let items=[],filtered=[],shown=0,category='All',query='';
let viewerItem=null,viewerImages=[],viewerIndex=0,viewerZoom=1;
const PAGE=24;
const SEARCH_GROUPS=[
 ['gas','cooker','stove','burner','cooking','kitchen'],['tv','television','screen','smart tv'],['fridge','refrigerator','freezer','cooler'],['sofa','couch','seat','chair','furniture'],['bed','mattress','bedroom'],['sufuria','cooking pot','pot','pan','cookware','kitchen'],['bicycle','bike','cycle','tricycle','tri-cycle','kids'],['shoe','shoes','sneaker','sandals','footwear'],['phone','mobile','smartphone','telephone'],['speaker','radio','music','sound','audio'],['iron','ironing','laundry'],['fan','cooling','air'],['table','desk','furniture'],['wardrobe','cabinet','cupboard','storage'],['baby','child','children','kids','toy']
];
function waUrl(text){return `https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(text)}`;}
function normalizeQuery(v){return String(v||'').toLowerCase().replace(/\bsufurias?\b/g,'cooking pot').trim();}
function searchTerms(v){const q=normalizeQuery(v);if(!q)return [];const words=q.split(/\s+/).filter(Boolean),out=new Set([q,...words]);for(const group of SEARCH_GROUPS){if(group.some(term=>q.includes(term)||words.includes(term)))group.forEach(term=>out.add(term));}return [...out];}
function basket(){try{return JSON.parse(localStorage.getItem('gongoniBasket')||'{}');}catch{return {};}}
function saveBasket(b){localStorage.setItem('gongoniBasket',JSON.stringify(b));updateBasket();}
function basketKey(i){return `${i.id||i.image}-${i.name}`;}
function addBasket(i){if(!inStock(i))return;const b=basket(),k=basketKey(i);if(!b[k])b[k]={item:i,qty:0};b[k].qty++;saveBasket(b);openBasket();}
function updateBasket(){const b=basket();const count=Object.values(b).reduce((s,e)=>s+Number(e.qty||0),0);$$('[data-basket-count]').forEach(n=>n.textContent=count);const box=$('#basketItems');if(!box)return;const rows=Object.values(b);box.innerHTML=rows.length?rows.map(({item,qty})=>`<article class="basket-item"><img src="${esc(thumb(item))}" alt="${esc(item.name)}"><div><strong>${esc(item.name)}</strong><small>${esc(item.category||'General goods')} - ${money(item.price)}</small><div class="qty-controls"><button type="button" data-dec="${esc(basketKey(item))}">-</button><span>${qty}</span><button type="button" data-inc="${esc(basketKey(item))}">+</button></div></div></article>`).join(''):'<p class="empty-basket">Your basket is empty.</p>';const subtotal=rows.reduce((s,e)=>s+(Number(e.item.price)||0)*e.qty,0);$('[data-basket-subtotal]')&&($('[data-basket-subtotal]').textContent=money(subtotal));$('[data-basket-delivery]')&&($('[data-basket-delivery]').textContent='Select delivery area');$('[data-basket-total]')&&($('[data-basket-total]').textContent=money(subtotal));$('[data-checkout-count]')&&($('[data-checkout-count]').textContent=`${count} items`);$('[data-checkout-subtotal]')&&($('[data-checkout-subtotal]').textContent=money(subtotal));$('[data-checkout-total]')&&($('[data-checkout-total]').textContent=money(subtotal));}
function openBasket(){const p=$('#basketPanel');if(p){p.classList.add('open');p.setAttribute('aria-hidden','false');}}
function closeBasket(){const p=$('#basketPanel');if(p){p.classList.remove('open');p.setAttribute('aria-hidden','true');}}
function openPay(i){const m=$('#paybillModal');if(!m)return;const area=$('[data-delivery-area]',m);if(area&&!area.options.length)area.innerHTML=DELIVERY_AREAS.map(x=>`<option value="${esc(x.area)}">${esc(x.area)} - ${x.fee?money(x.fee):'Free'}</option>`).join('');$('h2',m).textContent=i.name;$('[data-pay-amount]',m).textContent=money(i.price);const update=()=>{const d=DELIVERY_AREAS.find(x=>x.area===area?.value)||DELIVERY_AREAS[0],base=Number(i.price)||0;$('[data-delivery-fee]',m).textContent=d.fee?money(d.fee):'Free';$('[data-pay-total]',m).textContent=money(base+d.fee);$('[data-pay-note]',m).textContent=`Paybill ${PAYBILL} · Account ${ACCOUNT}. Confirm delivery before payment.`;$('[data-pay-whatsapp]',m).href=waUrl(`Hello Gongoni, I am paying for ${i.name}. Paybill ${PAYBILL}, Account ${ACCOUNT}.`);};area?.addEventListener('change',update);update();m.classList.add('open');m.setAttribute('aria-hidden','false');}
function renderViewerImage(){const v=$('#viewer');if(!v||!viewerImages.length)return;viewerIndex=(viewerIndex+viewerImages.length)%viewerImages.length;const img=$('.viewer-photo-wrap > img',v)||$('img',v);img.src=viewerImages[viewerIndex];img.style.transform=`scale(${viewerZoom})`;img.style.transformOrigin='center center';img.style.transition='transform .18s ease';img.style.cursor=viewerZoom>1?'zoom-out':'zoom-in';const prev=$('[data-viewer-prev]',v),next=$('[data-viewer-next]',v);if(prev)prev.hidden=viewerImages.length<2;if(next)next.hidden=viewerImages.length<2;const slides=$('.viewer-slides',v);if(slides)slides.textContent=viewerImages.length>1?`${viewerIndex+1} / ${viewerImages.length}`:'';$$('[data-vimg]',v).forEach((b,n)=>b.classList.toggle('active',n===viewerIndex));}
function setViewerZoom(z){viewerZoom=Math.max(1,Math.min(2.5,Number(z)||1));renderViewerImage();$$('[data-zoom]').forEach(b=>b.classList.toggle('active',Math.abs(Number(b.dataset.zoom)-viewerZoom)<0.001));}
function moveViewer(step){if(viewerImages.length<2)return;viewerIndex=(viewerIndex+step+viewerImages.length)%viewerImages.length;viewerZoom=1;renderViewerImage();}
function openViewer(i){const v=$('#viewer');if(!v||!i)return;viewerItem=i;viewerImages=imgs(i);viewerIndex=0;viewerZoom=1;const img=$('.viewer-photo-wrap > img',v)||$('img',v);img.alt=i.name;$('strong',v).textContent=i.name;$('[data-viewer-price]',v).textContent=money(i.price);$('.viewer-breadcrumb',v).textContent=`Home / ${i.category||'Products'}`;$('.viewer-meta',v).innerHTML=`<span>${inStock(i)?'In stock':'Out of stock'}</span><span>${viewerImages.length} photo${viewerImages.length===1?'':'s'}</span>`;$('p',v).textContent=`${i.name} is available at Gongoni Furniture Shop.`;const wa=$('.whatsapp-action',v);if(wa)wa.href=waUrl(`Hello Gongoni, I want to order ${i.name} at ${money(i.price)}.`);const add=$('[data-viewer-add]',v);if(add){add.onclick=()=>addBasket(i);add.disabled=!inStock(i);}const pay=$('[data-viewer-pay]',v);if(pay){pay.onclick=()=>openPay(i);pay.disabled=!inStock(i);}const thumbs=$('[data-viewer-thumbs]',v);if(thumbs)thumbs.innerHTML=viewerImages.map((src,n)=>`<button type="button" data-vimg="${n}" aria-label="View photo ${n+1}"><img src="${esc(src)}" alt=""></button>`).join('');renderViewerImage();v.classList.add('open');v.setAttribute('aria-hidden','false');}
function card(i){return `<article class="product-card"><button type="button" data-open-id="${esc(i.id)}"><img src="${esc(thumb(i))}" alt="${esc(i.name)}" loading="lazy" decoding="async">${imgs(i).length>1?`<span class="slide-count">1 / ${imgs(i).length}</span>`:''}</button><div class="badges"><span>${inStock(i)?'In stock':'Out of stock'}</span><span>${i.price!==null?'Price ready':'Ask price'}</span>${imgs(i).length>1?'<span>More photos</span>':''}</div><div><h3>${esc(i.name)}</h3><small>${/cooking\s*pot/i.test(`${i.name} ${i.caption||''}`)?'Kitchen - Sufuria':esc(i.category||'General goods')}</small></div><div class="price">${money(i.price)}</div><div class="item-meta"><span>+ delivery from KSh 100</span><span>No ratings yet</span></div><div class="card-actions"><button class="add-action" type="button" data-add-id="${esc(i.id)}" ${inStock(i)?'':'disabled'}>${inStock(i)?'Add to basket':'Out of stock'}</button><button class="paybill-action" type="button" data-pay-id="${esc(i.id)}" ${inStock(i)?'':'disabled'}>Direct Paybill</button></div><div class="card-extra-actions"><button class="buy-now" type="button" data-pay-id="${esc(i.id)}" ${inStock(i)?'':'disabled'}>Buy now</button><button type="button" data-wa-id="${esc(i.id)}">WhatsApp</button></div></article>`;}
function mergeKnownDuplicates(list){const pairs=[['Tri-Cycle Bicycle D 022','General Goods Item 019'],['Tri-Cycle Bicycle D 209','General Goods Item 017'],['Tri-Cycle Bicycle 015','General Goods Item 023']];const removed=new Set();for(const [primaryName,duplicateName] of pairs){const primary=list.find(i=>String(i.name||'').trim().toLowerCase()===primaryName.toLowerCase());const duplicate=list.find(i=>String(i.name||'').trim().toLowerCase()===duplicateName.toLowerCase());if(!primary||!duplicate)continue;primary.images=[...new Set([...imgs(primary),...imgs(duplicate)])];primary.image=primary.image||primary.images[0];primary.thumb=primary.thumb||primary.image;primary.category='Baby & kids';removed.add(duplicate);}return list.filter(i=>!removed.has(i));}
function apply(){const q=normalizeQuery(query),terms=searchTerms(query);const pool=items.filter(i=>category==='All'||i.category===category);if(!q){filtered=pool;}else{const scored=pool.map(i=>{const hay=`${i.name||''} ${i.category||''} ${i.caption||''}`.toLowerCase();let score=0;if(hay.includes(q))score+=100;for(const t of terms){if(hay.includes(t))score+=t===q?40:10;}return {i,score};}).filter(x=>x.score>0).sort((a,b)=>b.score-a.score);filtered=scored.map(x=>x.i);}shown=0;const g=$('#productGrid');if(g)g.innerHTML='';renderMore();$('#productCount')&&($('#productCount').textContent=`${filtered.length} products${q?' related to your search':''}`);const pg=$('#photoGrid');if(pg)pg.innerHTML='';$('#photoCount')&&($('#photoCount').textContent='');$('#loadMore')&&($('#loadMore').hidden=true);}
function renderMore(){const g=$('#productGrid');if(!g)return;const next=filtered.slice(shown,shown+PAGE);g.insertAdjacentHTML('beforeend',next.map(card).join(''));shown+=next.length;let b=$('#liteMore');if(!b){b=document.createElement('button');b.id='liteMore';b.className='load-more';b.type='button';b.textContent='Load more products';g.insertAdjacentElement('afterend',b);b.onclick=renderMore;}b.hidden=shown>=filtered.length;}
function setupCategories(){const cats=[...new Set(items.map(i=>i.category).filter(Boolean))].sort(),s=$('#categorySelect');if(s){s.innerHTML=`<option value="All">All categories (${items.length})</option>`+cats.map(c=>`<option value="${esc(c)}">${esc(c)}</option>`).join('');s.onchange=()=>{category=s.value;apply();};}}
function setupSearch(){const h=$('#headerSearchInput'),m=$('#searchInput'),btn=$('#headerSearchButton');const set=v=>{query=v||'';if(h&&h.value!==query)h.value=query;if(m&&m.value!==query)m.value=query;apply();};h&&(h.oninput=()=>set(h.value));m&&(m.oninput=()=>set(m.value));btn&&(btn.onclick=()=>set(h?.value||''));$$('[data-category-chip]').forEach(x=>x.onclick=e=>{e.preventDefault();category=x.dataset.categoryChip||'All';if($('#categorySelect'))$('#categorySelect').value=category;apply();});}
function wire(){document.addEventListener('click',e=>{const id=a=>items.find(i=>String(i.id)===String(a));const o=e.target.closest('[data-open-id]');if(o){openViewer(id(o.dataset.openId));return;}const a=e.target.closest('[data-add-id]');if(a){addBasket(id(a.dataset.addId));return;}const p=e.target.closest('[data-pay-id]');if(p){openPay(id(p.dataset.payId));return;}const w=e.target.closest('[data-wa-id]');if(w){const i=id(w.dataset.waId);window.open(waUrl(`Hello Gongoni, I want to order ${i.name} at ${money(i.price)}.`),'_blank','noopener');return;}const prev=e.target.closest('[data-viewer-prev]');if(prev){e.preventDefault();moveViewer(-1);return;}const next=e.target.closest('[data-viewer-next]');if(next){e.preventDefault();moveViewer(1);return;}const z=e.target.closest('[data-zoom]');if(z){e.preventDefault();setViewerZoom(z.dataset.zoom);return;}const vi=e.target.closest('[data-vimg]');if(vi){e.preventDefault();viewerIndex=Number(vi.dataset.vimg)||0;viewerZoom=1;renderViewerImage();return;}if(e.target.closest('.viewer-photo-wrap > img')){setViewerZoom(viewerZoom>1?1:1.5);return;}if(e.target.closest('[data-basket-open]'))openBasket();if(e.target.closest('[data-basket-close]'))closeBasket();if(e.target.closest('[data-close]')){const v=$('#viewer');v?.classList.remove('open');v?.setAttribute('aria-hidden','true');viewerZoom=1;}if(e.target.closest('[data-pay-close]')){const m=$('#paybillModal');m?.classList.remove('open');m?.setAttribute('aria-hidden','true');}const inc=e.target.closest('[data-inc]'),dec=e.target.closest('[data-dec]');if(inc||dec){const b=basket(),k=(inc||dec).dataset.inc||(inc||dec).dataset.dec;if(b[k]){b[k].qty+=(inc?1:-1);if(b[k].qty<=0)delete b[k];saveBasket(b);}}});const wrap=$('.viewer-photo-wrap');if(wrap){let sx=0,sy=0;wrap.addEventListener('touchstart',e=>{const t=e.changedTouches[0];sx=t.clientX;sy=t.clientY;},{passive:true});wrap.addEventListener('touchend',e=>{const t=e.changedTouches[0],dx=t.clientX-sx,dy=t.clientY-sy;if(Math.abs(dx)>45&&Math.abs(dx)>Math.abs(dy))moveViewer(dx<0?1:-1);},{passive:true});}$$('[data-whatsapp]').forEach(a=>{a.href=waUrl('Hello Gongoni, I want to place an order.');a.target='_blank';a.rel='noopener';});}
async function boot(){try{const r=await fetch(`all-photos-data.json?v=batch-14-d-drive-products-01`,{cache:'no-store'});if(!r.ok)throw new Error('catalog');const data=await r.json();items=mergeKnownDuplicates(Array.isArray(data)?data:[]);if(!items.length)throw new Error('empty');setupCategories();setupSearch();wire();updateBasket();apply();}catch(e){const g=$('#productGrid');if(g)g.innerHTML='<div style="padding:18px;background:#fff;border-radius:12px"><strong>Products could not load.</strong><p>Please refresh the page once.</p></div>';}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
